### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by caseros** [mm/pulse#3]
Hi,

Not sure what to put for:

> Paste callback URL you get back here

Thanks!

**Comment by mm** [comment]
Super sorry for the late response! When you first run the program (assuming everything's set up with Fitbit's site properly at dev.fitbit.com), you should see something similar to the following:

`Note: looks like we don't have an access token yet. Let's fetch one.
Please go to the following authorization URL: https://www.fitbit.com/oauth2/authorize?...(rest of URL is omitted)`

Copy and paste the URL you get into your browser. When you do, Fitbit should prompt you to log in to your account & authorize your application to access it. Once you've authorized it, you should be redirected to another URL, based on the callback URL you set up on dev.fitbit.com. Copy & paste this entire URL where you see 'Paste callback URL you get back here:' in Pulse.
